name: CI CD
on: [push]
jobs:
    deploy:
         name: deploy python script
      runs-on: ubuntu-latest
        steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: step one
           run: python hello.py

    build:
         name: building
      runs-on: ubuntu-latest
        needs: [deploy]
        steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Creating artifacts
           uses: actions/upload-artifact@v3
           with:
                name: ${{ env.ARTNAME }}
                path: .
